krs/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home_krs_view"),
    path('tambah/', tambah_krs, name="tambah_krs"),
    path('edit/<int:id>/', edit_krs, name="edit_krs"),
    path('delete/<int:id>/', hapus_krs, name="hapus_krs"),
]

matkul/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home_matkul_view"),
    path('tambah/', tambah_matkul, name="tambah_matkul"),
    path('edit/<int:id>/', edit_matkul, name="edit_matkul"),
    path('delete/<int:id>/', hapus_matkul, name="hapus_matkul"),
]

show/urls.py
from django.urls import path, include
from .views import login, logout, home, tampilan_admin, tampilan_mahasiswa, tampilan_dosen, dosen_manajemen_kelas, \
    dosen_manajemen_matkul, dosen_jadwal_mengajar, dosen_daftar_mahasiswa, dosen_tambah_matkul, dosen_edit_matkul, \
    dosen_kelola_matkul, dosen_hapus_matkul, dosen_tambah_kelas, dosen_edit_kelas, dosen_hapus_kelas, \
    mahasiswa_tambah_krs, mahasiswa_hapus_krs, mahasiswa_jadwal_kuliah, reset_matkul, dosen_get_detail_kelas, \
    dosen_manajemen_dosen, dosen_tambah_dosen, dosen_kelola_dosen, dosen_edit_dosen

urlpatterns = [

    path('home/', home, name='home_page'),
    path('', login, name='login_page'),
    path('logout/', logout, name='logout_page'),

    
    path('mahasiswa/', include([
        path('krs/',include([
            path('',tampilan_mahasiswa, name='tampilan_mahasiswa'),
            path('tambah', mahasiswa_tambah_krs, name='mahasiswa_tambah_krs'),
            path('delete/<int:id>/', mahasiswa_hapus_krs, name='mahasiswa_hapus_krs')
        ])),

        path('jadwal',mahasiswa_jadwal_kuliah, name='mahasiswa_jadwal_kuliah')

    ])),



    path('dosen/',include([
        # path('manajemen-kelas', dosen_manajemen_kelas, name='dosen_manajemen_kelas'),
        # path('', tampilan_dosen, name='tampilan_dosen'),
        path('manajemen-kelas/', include([
            path('', dosen_manajemen_kelas, name='dosen_manajemen_kelas'),
            # path('kelola', dosen_kelola_kelas, name='dosen_kelola_kelas'),
            path('tambah', dosen_tambah_kelas, name="dosen_tambah_kelas"),
            path('edit/<int:id>/', dosen_edit_kelas, name="dosen_edit_kelas"),
            path('delete/<int:id>/', dosen_hapus_kelas, name="dosen_hapus_kelas"),
            ])),
        path('manajemen-matkul/',include([
            path('', dosen_manajemen_matkul, name='dosen_manajemen_matkul'),
            path('kelola', dosen_kelola_matkul, name='dosen_kelola_matkul'),
            path('tambah', dosen_tambah_matkul, name="dosen_tambah_matkul"),
            path('reset', reset_matkul, name="reset_matkul"),
            path('edit/<int:id>/', dosen_edit_matkul, name="dosen_edit_matkul"),
            path('delete/<int:id>/', dosen_hapus_matkul, name="dosen_hapus_matkul"),
            ])),
        path('manajemen-dosen/',include([
            path('',dosen_manajemen_dosen, name='dosen_manajemen_dosen'),
            path('kelola', dosen_kelola_dosen, name='dosen_kelola_dosen'),
            path('tambah',dosen_tambah_dosen, name='dosen_tambah_dosen'),
            path('edit/<int:id>/',dosen_edit_dosen, name='dosen_edit_dosen'),


        ])),

        path('jadwal-mengajar', dosen_jadwal_mengajar, name='dosen_jadwal_mengajar'),
        path('jadwal-mengajar/detail/<int:id>/', dosen_get_detail_kelas, name="dosen_get_detail_kelas"),
        path('daftar-mahasiswa', dosen_daftar_mahasiswa, name='dosen_daftar_mahasiswa')


        # path('tambah', tambah_dosen, name="tambah_dosen"),
        # path('edit/<int:id>/', edit_dosen, name="edit_dosen"),
        # path('delete/<int:id>/', hapus_dosen, name="hapus_dosen"),
    ]))

    # path('dosen/',include(
    #         path()
    #     ))

    # path('aktor/', include('aktor.urls')),
    # path('jadwal/', include('jadwal.urls')),
    # path('krs/', include('krs.urls')),
    # path('matkul/', include('matkul.urls')),
    # path('prodi/', include('prodi.urls')),
    # path('',include('show.urls')),
]

sia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aktor/', include('aktor.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('krs/', include('krs.urls')),
    path('matkul/', include('matkul.urls')),
    path('prodi/', include('prodi.urls')),
    path('',include('show.urls')),

]

matkul/models.py
from django.db import models
from prodi.models import Prodi
from django.db.models import IntegerField, Model
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
JENIS_MATKUL = (
    (0, 'Praktikum'),
    (1, 'Teori')
)
SEMESTER = (
    (1, 'Satu'),
    (2, 'Dua'),
    (3, 'Tiga'),
    (4, 'Empat'),
    (5, 'Lima'),
    (6, 'Enam'),
    (7, 'Tujuh'),
    (8, 'Delapan'),
    (9, 'Pilihanganjil'),
    (10, 'Pilihangenap'),
    (11, 'GanjilGenap')
)

class Matkul(models.Model):
    kode = models.CharField(max_length=10, unique=True)
    nama = models.CharField(max_length=256)
    semester = models.PositiveIntegerField(default=9, choices = SEMESTER)
    sks = models.IntegerField(
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ]
     )
    # sks = models.PositiveSmallIntegerField()
    is_aktif = models.BooleanField(default=True)
    prodi = models.ForeignKey(Prodi, on_delete=models.CASCADE)  # untuk MKDU nama prodi adalah Universitas
    jenis = models.PositiveSmallIntegerField(default=1, choices=JENIS_MATKUL)
    def __str__(self):
        return '{}'.format(self.nama)

    class Meta:
        verbose_name_plural = "Mata kuliah"
        verbose_name = "Mata kuliah"

show/models.py
from django.db import models

# Create your models here.

matkul/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ('kode', 'nama', 'sks', 'semester', 'is_aktif', 'jenis')

matkul/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import MatkulForm
from prodi.models import Prodi
# Create your views here.
from aktor.models import Dosen
from .models import Matkul

def home(request):
    if request.user.is_authenticated:
        try:
            matkul = Matkul.objects.filter(prodi= request.user.dosen.prodi)

        except Dosen.DoesNotExist:
            if  request.user.mahasiswa:
                matkul = Matkul.objects.filter(prodi= request.user.mahasiswa.prodi)

    else :
        matkul = Matkul.objects.all()
    return render(request, 'matkul.html', {'matkul' : matkul})

@login_required(login_url='/show/')
def tambah_matkul(request):
    try:
        if request.user.groups.filter(name='Kaprodi').exists():
            prodi_dosen = request.user.dosen.prodi
            mk = Matkul(prodi=prodi_dosen)
            # print('asdna')
            if request.method == 'POST':
                form = MatkulForm(request.POST, instance=mk)
                if form.is_valid():
                    # print(request.POST.getlist('kode'))
                    form.save()
                    return redirect('home_matkul_view')
            else:
                form = MatkulForm(instance=mk)

            return render(request, 'matkul_form.html', {'form':form})
        else :
            return redirect('home_matkul_view')
    except Exception as eror:
        print(eror)
        return redirect('home_matkul_view')

@login_required(login_url='/show/')
def edit_matkul(request, id):
    try:
        if request.user.groups.filter(name='Kaprodi').exists():
            matkul = Matkul.objects.get(id = id)
            form = MatkulForm(request.POST or None, instance = matkul)

            if form.is_valid():
                form.save()
                return redirect('home_matkul_view')

            return render(request, 'matkul_form.html', {'form':form, 'matkul':matkul})
        else:
            return redirect('home_matkul_view')
    except Exception as eror:
        print(eror)
        return redirect('home_matkul_view')

@login_required(login_url='/show/')
def hapus_matkul(request,id):
    matkul = Matkul.objects.get(id=id)

    if  request.method=="POST":
        matkul.delete()
        return redirect('home_matkul_view')

    return render(request, 'aktor_delete.html', {'matkul' : matkul})

show/templates/kaprodi/manajemen_matkul/kelola_matkul.html
{% extends "base/base.html" %}

{% load static %}

{% block link %}
    <!-- Footable CSS -->
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/css/footable.core.css"
          rel="stylesheet">
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.css"
          rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock link %}
{% block judul %}
    Manajemen Mata Kuliah
{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'home_page' %}">home</a></li>
    <li><a href="{% url 'dosen_manajemen_matkul' %}">Manajemen Matakuliah</a></li>
    <li>Kelola</li>
{% endblock %}

{% block content %}
    <div class="row text-right" style="padding-right: 15px">
        <a href="{% url 'dosen_tambah_matkul' %}">
            <button class="text-right btn btn-success">tambah baru</button>
        </a>
    </div>

    <h3 class="box-title m-b-0">Matakuliah yang ditawarkan</h3>
    <form method="post">{% csrf_token %}
        <table id="makul">
            <thead>
            <tr>
                <th> Kode</th>
                <th> Nama</th>
                <th> Jenis</th>
                <th> Jumlah SKS</th>
                <th> Status</th>
                <th>action</th>
            </tr>
            </thead>

            <tbody>
            {% for makul in matkul %}
                <tr>

                    <td>{{ makul.kode }}</td>
                    <td>{{ makul.nama }}</td>
                    <td>{{ makul.get_jenis_display }}</td>
                    <td>{{ makul.sks }}</td>

                    {% if makul.is_aktif == 1 %}
                        <td><span class="label label-table label-success">Ditawarkan</span></td>
                        <td><input name="checks" type="checkbox" checked value="{{ makul.id }}"/>
                            <a href="{% url 'dosen_edit_matkul' makul.id %}">
                                <span><i class="fa fa-pencil-square-o fa-2x"></i></span>
                            </a></td>
                        </td>
                    {% else %}
                        <td><span class="label label-table label-danger">Tidak Ditawarkan</span></td>
                        <td><input name="checks" type="checkbox" value="{{ makul.id }}"/>
                            <a href="{% url 'dosen_edit_matkul' makul.id %}"><span><i
                                    class="fa fa-pencil-square-o fa-2x"></i></span></a></td>
                    {% endif %}


                </tr>
            {% endfor %}


            </tbody>
        </table>
        <br>
        <button class="btn btn-info" type="submit">Simpan</button>
        <button class="btn btn-warning" type="reset">Reset</button>
        <a href="{% url 'reset_matkul' %}"><span class="btn btn-danger">Clear</span></a>
    </form>
    <div class="col-sm-12 text-right m-b-20">
        <div class="form-group"></div>
    </div>
    </div>
    </div>


{% endblock content %}


{% block javascript %}
    <!-- Footable -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/js/footable.all.min.js"></script>
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.js"
            type="text/javascript"></script>
    <!--FooTable init-->
    <script src="{% static 'js/footable-init.js' %}"></script>
    <!--Style Switcher -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#makul').DataTable({
            "order": [ ]

            });

        });
    </script>

{% endblock javascript %}

show/templates/kaprodi/manajemen_matkul/manajemen_matkul.html
{% extends "base/base.html" %}

{% load static %}

{% block link %}
	<!-- Footable CSS -->
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/css/footable.core.css" rel="stylesheet">
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />
{% endblock link %}
    
{% block judul %}
    Manajemen Mata Kuliah
{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'home_page' %}">home</a></li>
    <li>Manajemen Matakuliah</li>
{% endblock %}
{% block content %}
	
                                <div class="form-inline padding-bottom-15">
                                    <div class="row">
                                
                                        <div class="col-sm-12 text-right m-b-20">
                                            <div class="form-group">
                                                <a href="{%  url 'dosen_kelola_matkul' %}">
                                                    <button id="demo-btn-addrow" class="btn btn-success active btn-block">
                                                        <i class="icon wb-plus" aria-hidden="true"></i>Kelola Matakuliah</button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            <h3 class="box-title m-b-0">Matakuliah yang ditawarkan</h3>

                            <table id="demo-foo-accordion" class="table m-b-10 ">
                                <thead>
                                    <tr>
                                        <th data-toggle="true"> Kode </th>
                                        <th> Nama </th>
                                        <th data-hide="phone"> Jenis </th>
                                        <th data-hide="all"> Jumlah SKS </th>
                                        <th data-hide="all"> Status </th>
                                    </tr>
                                </thead>
                                <tbody>
                                	{% for makul in matkul  %}
                                		<tr>
	                                        <td>{{makul.kode}}</td>
	                                        <td>{{makul.nama}}</td>
	                                        <td>{{makul.get_jenis_display}}</td>
	                                        <td>{{makul.sks}}</td>
	                                        <td><span class="label label-table label-success">Ditawarkan</span></td>
	                                    </tr>
                                	{% endfor %}
                                    
                                </tbody>
                            </table>

{% endblock content %}


{% block javascript %}
	    <!-- Footable -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/js/footable.all.min.js"></script>
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
    <!--FooTable init-->
    <script src="{% static 'js/footable-init.js' %}"></script>
    <!--Style Switcher -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>

{% endblock javascript %}

show/templates/kaprodi/manajemen_matkul/matkul_form.html
{% extends "base/base.html" %}

{% load static %}
{% load bootstrap3 %}
{% block link %}
    {% bootstrap_messages %}
    	<!-- Footable CSS -->
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/css/footable.core.css" rel="stylesheet">
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />

{% endblock link %}
{% block judul %}
    Manajemen Mata Kuliah
{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'home_page' %}">home</a></li>
    <li><a href="{% url 'dosen_manajemen_matkul' %}">Manajemen Matakuliah</a></li>
    <li><a href="{% url 'dosen_kelola_matkul' %}">Kelola</a></li>
    {% if matkul %}
    <li>edit</li>
    {% else %}
    <li>tambah</li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Tambah / Edit Mata Kuliah</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        {% buttons %}
            <button type="submit" class="btn btn-success btn-block">Simpan</button>
        {% endbuttons %}
    </form>
{#    </div>#}

    {% if matkul %}

        <a href="{% url 'hapus_matkul' matkul.id %}"><button class="btn btn-danger">DELETE</button></a>

    {% endif %}
</div>
{% endblock content %}


{% block javascript %}
	    <!-- Footable -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/js/footable.all.min.js"></script>
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
    <!--FooTable init-->
    <script src="{% static 'js/footable-init.js' %}"></script>
    <!--Style Switcher -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>

{% endblock javascript %}