krs/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home_krs_view"),
    path('tambah/', tambah_krs, name="tambah_krs"),
    path('edit/<int:id>/', edit_krs, name="edit_krs"),
    path('delete/<int:id>/', hapus_krs, name="hapus_krs"),
]

show/urls.py
from django.urls import path, include
from .views import login, logout, home, tampilan_admin, tampilan_mahasiswa, tampilan_dosen, dosen_manajemen_kelas, \
    dosen_manajemen_matkul, dosen_jadwal_mengajar, dosen_daftar_mahasiswa, dosen_tambah_matkul, dosen_edit_matkul, \
    dosen_kelola_matkul, dosen_hapus_matkul, dosen_tambah_kelas, dosen_edit_kelas, dosen_hapus_kelas, \
    mahasiswa_tambah_krs, mahasiswa_hapus_krs, mahasiswa_jadwal_kuliah, reset_matkul, dosen_get_detail_kelas, \
    dosen_manajemen_dosen, dosen_tambah_dosen, dosen_kelola_dosen, dosen_edit_dosen

urlpatterns = [

    path('home/', home, name='home_page'),
    path('', login, name='login_page'),
    path('logout/', logout, name='logout_page'),

    
    path('mahasiswa/', include([
        path('krs/',include([
            path('',tampilan_mahasiswa, name='tampilan_mahasiswa'),
            path('tambah', mahasiswa_tambah_krs, name='mahasiswa_tambah_krs'),
            path('delete/<int:id>/', mahasiswa_hapus_krs, name='mahasiswa_hapus_krs')
        ])),

        path('jadwal',mahasiswa_jadwal_kuliah, name='mahasiswa_jadwal_kuliah')

    ])),



    path('dosen/',include([
        # path('manajemen-kelas', dosen_manajemen_kelas, name='dosen_manajemen_kelas'),
        # path('', tampilan_dosen, name='tampilan_dosen'),
        path('manajemen-kelas/', include([
            path('', dosen_manajemen_kelas, name='dosen_manajemen_kelas'),
            # path('kelola', dosen_kelola_kelas, name='dosen_kelola_kelas'),
            path('tambah', dosen_tambah_kelas, name="dosen_tambah_kelas"),
            path('edit/<int:id>/', dosen_edit_kelas, name="dosen_edit_kelas"),
            path('delete/<int:id>/', dosen_hapus_kelas, name="dosen_hapus_kelas"),
            ])),
        path('manajemen-matkul/',include([
            path('', dosen_manajemen_matkul, name='dosen_manajemen_matkul'),
            path('kelola', dosen_kelola_matkul, name='dosen_kelola_matkul'),
            path('tambah', dosen_tambah_matkul, name="dosen_tambah_matkul"),
            path('reset', reset_matkul, name="reset_matkul"),
            path('edit/<int:id>/', dosen_edit_matkul, name="dosen_edit_matkul"),
            path('delete/<int:id>/', dosen_hapus_matkul, name="dosen_hapus_matkul"),
            ])),
        path('manajemen-dosen/',include([
            path('',dosen_manajemen_dosen, name='dosen_manajemen_dosen'),
            path('kelola', dosen_kelola_dosen, name='dosen_kelola_dosen'),
            path('tambah',dosen_tambah_dosen, name='dosen_tambah_dosen'),
            path('edit/<int:id>/',dosen_edit_dosen, name='dosen_edit_dosen'),


        ])),

        path('jadwal-mengajar', dosen_jadwal_mengajar, name='dosen_jadwal_mengajar'),
        path('jadwal-mengajar/detail/<int:id>/', dosen_get_detail_kelas, name="dosen_get_detail_kelas"),
        path('daftar-mahasiswa', dosen_daftar_mahasiswa, name='dosen_daftar_mahasiswa')


        # path('tambah', tambah_dosen, name="tambah_dosen"),
        # path('edit/<int:id>/', edit_dosen, name="edit_dosen"),
        # path('delete/<int:id>/', hapus_dosen, name="hapus_dosen"),
    ]))

    # path('dosen/',include(
    #         path()
    #     ))

    # path('aktor/', include('aktor.urls')),
    # path('jadwal/', include('jadwal.urls')),
    # path('krs/', include('krs.urls')),
    # path('matkul/', include('matkul.urls')),
    # path('prodi/', include('prodi.urls')),
    # path('',include('show.urls')),
]

sia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aktor/', include('aktor.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('krs/', include('krs.urls')),
    path('matkul/', include('matkul.urls')),
    path('prodi/', include('prodi.urls')),
    path('',include('show.urls')),

]

jadwal/models.py
from django.db import models
from matkul.models import Matkul
from aktor.models import Dosen
from prodi.models import Ruang

SEMESTER = (
    (1, 'Ganjil'),
    (2, 'Genap'),
)

URUTAN = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D')
)

HARI = (
    (2, 'Senin'),
    (3, 'Selasa'),
    (4, 'Rabu'),
    (5, 'Kamis'),
    (6, 'Jumat'),
    (7, 'Sabtu'),
)

SLOT_WAKTU = (
    (1, '07.00 - 07.50'),
    (2, '07.50 - 08.40'),
    (3, '08.40 - 09.30'),
    (4, '09.30 - 10.20'),
    (5, '10.20 - 11.10'),
    (6, '11.10 - 12.00'),
    (7, '12.30 - 13.20'),
    (8, '13.20 - 14.10'),
    (9, '14.10 - 15.00'),
    (10, '15.20 - 16.10'),
    (11, '16.10 - 17.00'),
    (12, '17.00 - 17.50'),
    (13, '18.20 - 19.10'),
    (14, '19.10 - 20.00'),
    (15, '20.00 - 20.50'),
    (15, '20.50 - 21.40'),

)


class Periode(models.Model):
    kode = models.CharField(max_length=10)
    tahun = models.PositiveIntegerField()
    semester = models.PositiveSmallIntegerField(choices=SEMESTER)

    def __str__(self):
        return '{}{}'.format(self.tahun, self.semester)

    class Meta:
        verbose_name_plural = "Periode"
        verbose_name = "Periode"

class JamKuliah(models.Model):
    hari = models.PositiveSmallIntegerField(choices=HARI)
    slot = models.PositiveSmallIntegerField(choices=SLOT_WAKTU)

    class Meta:
        verbose_name_plural = "Jam Kuliah"
        verbose_name = "Jam Kuliah"
        unique_together = ("hari", "slot")

    def __str__(self):
        return '{} : {}'.format(self.get_hari_display(), self.get_slot_display())

class JamDosen(models.Model):
    periode =models.ForeignKey(Periode, on_delete=models.CASCADE)
    dosen = models.ForeignKey(Dosen, on_delete=models.CASCADE)
    jam_kuliah = models.ManyToManyField(JamKuliah)

    class Meta:
        unique_together = ('periode','dosen')

class Kelas(models.Model):
    matkul = models.ForeignKey(Matkul, on_delete=models.CASCADE)
    periode = models.ForeignKey(Periode, on_delete=models.CASCADE)
    dosen = models.ManyToManyField(Dosen)
    ruang = models.ForeignKey(Ruang, on_delete=models.CASCADE, null=True)
    jam_kuliah = models.ForeignKey(JamKuliah, on_delete=models.CASCADE)
    nama = models.CharField(max_length=2,choices=URUTAN, default='A')  # A, B, C dst...
	# is_penuh = models.BooleanField(default=False)
    kapasitas = models.PositiveSmallIntegerField(default=40)
    # jam = jam()

    def jam(self):
        jam = set()
        hari_kamus={
            1 : 'Senin',
            2 : 'Selasa',
            3 : 'Rabu',
            4 : 'Kamis',
            5 : 'Jumat',
            6 : 'Sabtu'
        }
        # print(self.matkul)
        for i in range(self.matkul.sks):
            # print(i)
            jam.add(hari_kamus[self.jam_kuliah.hari-1]+str(self.jam_kuliah.slot+i))
        # print('aw')
        return jam


    class Meta:
        verbose_name_plural = "Kelas"
        verbose_name = "Kelas"
        unique_together = (('matkul', 'periode', 'nama'),
						   ('periode','ruang','jam_kuliah'))


    def __str__(self):
        return '{}:{}'.format(self.matkul.nama, self.nama)

show/models.py
from django.db import models

# Create your models here.

show/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Sum
from django.http import HttpResponse

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.views import logout
from django.core import serializers
from django.core.serializers import serialize


from aktor.models import Dosen, Mahasiswa
from jadwal.forms import KelasForm , JamDosenForm
from jadwal.models import Kelas, Periode, JamKuliah, JamDosen
from krs.forms import KrsForm
from krs.models import Krs, Sks_ips
from matkul.forms import MatkulForm
from matkul.models import Matkul
from django.contrib.auth.models import User

import random
import json
###### decorator yang dibuat#########
from prodi.models import Ruang


def cek_kaprodi(request):
	# print(request.groups.filter(name='Kaprodi').exists())
	return request.groups.filter(name='Kaprodi').exists()


def cek_mhs(request):
	try:
		if request.mahasiswa:
			return True
	except Exception as Error:
		print(Error)
		return False


def cek_dosen(request):
	try:
		if request.dosen:
			return True
	except Exception as Error:
		print(Error)
		return False


#################################

################ validasi global ################
def cek_sks(sks_mhs, sks_now, sks_matkul):
	if sks_now == None:
		return True
	elif sks_now + sks_matkul <= sks_mhs:
		print(sks_now + sks_matkul)
		return True
	else:
		print(sks_now + sks_matkul)
		return False


###################################


@login_required(login_url='/')
def home(request):
	return render(request, "beranda.html")


def tampilan_admin(request):
	template_name = 'admin_home.html'
	contex = {}
	return render(request, template_name, contex)


@user_passes_test(cek_kaprodi, login_url='/')
def reset_matkul(request):
	periode = Periode.objects.all().order_by('id').reverse()[0]
	semester = [2, 4, 6, 8, 10]  # sebagai validasi yang diambil semester genap
	if periode.semester == 2:
		Matkul.objects.filter(prodi=request.user.dosen.prodi, semester__in=semester).update(is_aktif=True)
		Matkul.objects.filter(prodi=request.user.dosen.prodi).exclude(semester__in=semester).update(is_aktif=False)
		Matkul.objects.filter(prodi=request.user.dosen.prodi, semester=11).update(is_aktif=True)
	else:
		Matkul.objects.filter(prodi=request.user.dosen.prodi, semester__in=semester).update(is_aktif=False)
		Matkul.objects.filter(prodi=request.user.dosen.prodi).exclude(semester__in=semester).update(is_aktif=True)
		Matkul.objects.filter(prodi=request.user.dosen.prodi, semester=11).update(is_aktif=True)
	return redirect('dosen_kelola_matkul')


def login(request):
	if request.user.is_authenticated:
		return redirect('home_page')

	template_name = 'login.html'
	context = {}

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		print(username)
		print(password)
		user = authenticate(username=username, password=password)

		if user is not None:
			auth_login(request, user)
			return redirect('home_page')
		else:
			context.update({'error_message': 'User tidak ada!'})
			return render(request, template_name, context)
	return render(request, template_name, context)


def logout(request):
	auth_logout(request)
	return redirect('login_page')

####################### view untuk dosen dan kaprodi ###############################
def tampilan_dosen(request):
	pass
	# return render(request,)


@user_passes_test(cek_kaprodi, login_url='/')
def dosen_manajemen_kelas(request):
	# kelas = Kelas.objects.all()
	# print(request.groups.filter(name='Kaprodi').exists())
	periode = Periode.objects.latest('id')
	template_name = 'kaprodi/manajemen_kelas/manajemen_kelas.html'

	def get_kelas_by_hari(hari):
		return Kelas.objects.filter(jam_kuliah__hari=hari, matkul__prodi=request.user.dosen.prodi, periode=periode)

	context = {
		'kelas_hari_senin': get_kelas_by_hari(2),
		'kelas_hari_selasa': get_kelas_by_hari(3),
		'kelas_hari_rabu': get_kelas_by_hari(4),
		'kelas_hari_kamis': get_kelas_by_hari(5),
		'kelas_hari_jumat': get_kelas_by_hari(6),
		'kelas_hari_sabtu': get_kelas_by_hari(7)
	}

	return render(request, template_name, context)


@user_passes_test(cek_kaprodi, login_url='/')
def dosen_tambah_kelas(request):
	template_name = 'kaprodi/manajemen_kelas/kelas_form.html'
	dosen_list = Dosen.objects.filter(prodi=request.user.dosen.prodi)
	matkul_list = Matkul.objects.filter(prodi=request.user.dosen.prodi, is_aktif=1)
	try:  # ini logika apakah matakuliah pada kelas tertentu apakah pernah dibuat
		if request.user.groups.filter(name='Kaprodi').exists():
			periode = Periode.objects.all().order_by('id').reverse()[0]
			jam = JamKuliah.objects.order_by('?')

			# print(jam)

			if request.method == 'POST':
				ruang = Ruang.objects.filter(kapasitas__gte=request.POST.get('kapasitas')).order_by('?')
				kelas = Kelas.objects.filter(periode=periode,matkul__prodi=request.user.dosen.prodi)
				jamdosen = JamDosen.objects.all().values_list('dosen__user', flat=True)
				# if 
				cek= JamDosen.objects.filter(periode=periode, dosen = request.POST.get('dosen'))
				# print(cek[0].jam_kuliah.all())
				cekset = set(str(x) for x in jamdosen)
				# print(request.POST.get('dosen'))
				print(cekset)
				cekdosen = set(request.POST.get('dosen'))
				print(cekdosen)
				if cekdosen & cekset:
					print(cek[0].jam_kuliah.all())

					jam = cek[0].jam_kuliah.all()
				jam_banned = set()
				for k in kelas:
					jam_banned = jam_banned | k.jam()
				print(jam_banned)
				form = KelasForm(request.POST)
				form.fields['dosen'].queryset = dosen_list
				form.fields['matkul'].queryset = matkul_list

				if form.is_valid():
					# ini untuk logika validasi dosen tidak boleh mengajar pada waktu bersamaan
					dosen = request.POST.getlist('dosen')
					matkul = Matkul.objects.get(id=request.POST.get('matkul'))
					sks_matkul = matkul.sks  # mencari jumlah sks makul yang dipilih

					for x in jam:
						# print(x)
						if Kelas.objects.filter(dosen__id__in=dosen, jam_kuliah=x, periode=periode).exists():
							continue
						else:
							# ini logika agar ruang tidak dapat dipadkai dalam waktu yang bersamaan
							for y in ruang:
								if Kelas.objects.filter(jam_kuliah=x, ruang=y, periode=periode).exists():
									continue
								else:
									kls = Kelas(jam_kuliah=x, ruang=y, periode=periode)
									form = KelasForm(request.POST, instance=kls)
									# print(form.jam())

									if form.is_valid():
										instance = form.save(commit=False)
										instance.nama = str(request.POST.get('nama')).upper()
										# print(type(instance.jam()))
										if jam_banned & instance.jam():
											print(instance.jam_kuliah)
											# print('a')
											continue
										else:
											print(instance.jam_kuliah)
											instance.save()
											form.save()
											return redirect('dosen_manajemen_kelas')
							# context = {'error_message': 'Semua kelas telah penuh !!!!!!', 'form': form}
							# return render(request, template_name, context)
					form.fields['dosen'].queryset = dosen_list
					form.fields['matkul'].queryset = matkul_list
					context = {'error_message': 'Jam dosen ini sudah penuh / tidak ada ruang yang tersedia', 'form': form}
					return render(request, template_name, context)
				else:

					context = {'form_errors': form.errors, 'form': form}
					return render(request, template_name, context)
			else:
				form = KelasForm()
				form.fields['dosen'].queryset = dosen_list
				form.fields['matkul'].queryset = matkul_list

			return render(request, template_name, {'form': form})
		else:
			return redirect('dosen_manajemen_kelas')
	except Exception as eror:
		print(eror)
		form = KelasForm(request.POST)
		form.fields['dosen'].queryset = dosen_list
		form.fields['matkul'].queryset = matkul_list
		context = {'error_message': 'Kelas Sudah tersedia', 'form': form}
		return render(request, template_name, context)


@user_passes_test(cek_kaprodi, login_url='/')
def dosen_edit_kelas(request, id):
	kelas = Kelas.objects.get(id=id)
	form = KelasForm(request.POST or None, instance=kelas)

	if form.is_valid():
		form.save()
		return redirect('home_kelas_view')

	return render(request, 'kelas_form.html', {'form': form, 'kelas': kelas})


@user_passes_test(cek_kaprodi, login_url='/')
def dosen_hapus_kelas(request, id):
	kelas = Kelas.objects.get(id=id)

	if request.method == "POST":
		kelas.delete()
		return redirect('home_kelas_view')

	return render(request, 'aktor_delete.html', {'kelas': kelas})


@user_passes_test(cek_kaprodi, login_url='/')
def dosen_manajemen_matkul(request):
	matkul = Matkul.objects.filter(is_aktif=True).filter(prodi=request.user.dosen.prodi)
	return render(request, 'kaprodi/manajemen_matkul/manajemen_matkul.html', {'matkul': matkul})

@user_passes_test(cek_kaprodi, login_url='/')
def dosen_kelola_matkul(request):
	if request.method == 'POST':
		id_list = request.POST.getlist('checks')
		Matkul.objects.filter(id__in=id_list).update(is_aktif=True)
		Matkul.objects.filter(prodi=request.user.dosen.prodi).exclude(id__in=id_list).update(is_aktif=False)

	matkul = Matkul.objects.filter(prodi=request.user.dosen.prodi).order_by('-id')
	return render(request, 'kaprodi/manajemen_matkul/kelola_matkul.html', {'matkul': matkul})


@user_passes_test(cek_kaprodi, login_url='/')
def dosen_tambah_matkul(request):
	try:
		# print(request.user.groups.filter(name='Kaprodi').exists())
		if request.user.groups.filter(name='Kaprodi').exists():
			prodi_dosen = request.user.dosen.prodi
			mk = Matkul(prodi=prodi_dosen)
			# print('asdna')
			if request.method == 'POST':
				form = MatkulForm(request.POST, instance=mk)
				if form.is_valid():
					# print(request.POST.getlist('kode'))
					form.save()
					return redirect('dosen_kelola_matkul')
			else:
				form = MatkulForm(instance=mk)

			return render(request, 'kaprodi/manajemen_matkul/matkul_form.html', {'form': form})

show/templates/kaprodi/manajemen_dosen/kelola_dosen.html
{% extends "base/base.html" %}
{% block title %}
    Kaprodi | Kelola Dosen
{% endblock title %}
{% block link %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">

{% endblock link %}
{% block breadcrumb %}
    <li><a href="{% url 'home_page' %}">home</a></li>
    <li><a href="{% url 'dosen_manajemen_dosen' %}">Manajemen Dosen</li></a>
    <li>kelola</li>
{% endblock %}
{% block judul %}
    Manajemen Dosen
{% endblock judul %}
{% block content %}
    <div class="row text-right" style="padding-right: 15px"><a href="{% url 'dosen_tambah_dosen' %}">
        <button class="btn btn-success active">Tambah dosen</button>
    </a></div>
    {# <hr> #}
    {# <div class="row"><a href="{% url 'dosen_tambah_dosen'%}"><button type="button">tambah</button></a></div> #}
    <div class="row">
    <div class="container">
    <h2>Daftar Dosen yang tersedia</h2>
    <hr>
    <div class="col-md-6">
        <table id="jamdos">
            <thead>
            <tr>
                <th>Nama Dosen</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for detail in jamdos %}
                <tr>
                    <td>{{ detail.dosen }}</td>
                    <td><a href="{% url 'dosen_edit_dosen' detail.id%}"><i class="fa fa-edit"></i>edit</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#jamdos').DataTable({
                "order": []

            });

        });
    </script>

{% endblock javascript %}

show/templates/kaprodi/manajemen_dosen/tambah_dosen.html
{% extends "base/base.html" %}

{% load static %}
{% load bootstrap3 %}
{% block link %}
    {% bootstrap_messages %}
      <!-- Footable CSS -->
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/css/footable.core.css" rel="stylesheet">
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />
    <link href="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/multiselect/css/multi-select.css" rel="stylesheet" type="text/css" />

<style type="text/css" media="screen">
	.ms-container{
  width: 100%;
}
</style>
{% endblock link %}

{% block judul %}
Manajemen Dosen
{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'home_page' %}">home</a></li>
    <li><a href="{% url 'dosen_manajemen_dosen' %}">Manajemen Dosen</a></li>
    <li>Form</li>
{% endblock %}
{% block content %}
	{% if message_success %}
		<span class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-success myadmin-alert-top alerttop" style="display: block;"> <i class="ti-user"></i> {{message_success}} <a href="#" class="closed">×</a> </span>
	{% endif %}
	{% if message_failed %}
		<span class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-danger myadmin-alert-top alerttop" style="display: block;"> <i class="ti-user"></i> {{message_failed}} <a href="#" class="closed">×</a> </span>
	{% endif %}
	{% if jamdos %}
	    <h1> Edit Jam Dosen</h1>
	{% else %}
    	<h1>Tambah Dosen</h1>>
	{% endif %}


    {% if error_message %}
      <div class="alert alert-warning">{{ error_message }}</div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
    {% if jamdos %}
        {% buttons %}
            <button type="submit" class="btn btn-success active btn-block">Simpan</button>
        {% endbuttons %}
        {% else %}
        {% buttons %}
            <button type="submit" class="btn btn-success active btn-block">Tambah</button>
        {% endbuttons %}
    {% endif %}

    </form>
 


    {% if jamdos %}

{#        <a href="{% url 'hapus_jamdos' jamdos.id %}"><button class="btn btn-danger">DELETE</button></a>#}

    {% endif %}
</div>
{% endblock content %}


{% block javascript %}
      <!-- Footable -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/footable/js/footable.all.min.js"></script>
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
    <!--FooTable init-->
    <script src="{% static 'js/footable-init.js' %}"></script>
    <!--Style Switcher -->
    <script src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>
            <script type="text/javascript" src="https://wrappixel.com/ampleadmin/ampleadmin-html/plugins/bower_components/multiselect/js/jquery.multi-select.js"></script>

    <script type="text/javascript">
    //Alerts
    $(".myadmin-alert .closed").click(function(event) {
        $(this).parents(".myadmin-alert").fadeToggle(350);
        return false;
    });
    /* Click to close */
    $(".myadmin-alert-click").click(function(event) {
        $(this).fadeToggle(350);
        return false;
    });
    $(".showtop").click(function() {
        $(".alerttop").fadeToggle(350);
    });
    $(".showtop2").click(function() {
        $(".alerttop2").fadeToggle(350);
    });
    /** Alert Position Bottom  **/
    $(".showbottom").click(function() {
        $(".alertbottom").fadeToggle(350);
    });
    $(".showbottom2").click(function() {
        $(".alertbottom2").fadeToggle(350);
    });
    /** Alert Position Top Left  **/
    $("#showtopleft").click(function() {
        $("#alerttopleft").fadeToggle(350);
    });
    /** Alert Position Top Right  **/
    $("#showtopright").click(function() {
        $("#alerttopright").fadeToggle(350);
    });
    /** Alert Position Bottom Left  **/
    $("#showbottomleft").click(function() {
        $("#alertbottomleft").fadeToggle(350);
    });
    /** Alert Position Bottom Right  **/
    $("#showbottomright").click(function() {
        $("#alertbottomright").fadeToggle(350);
    });
        $('#id_jam_kuliah').multiSelect();

    </script>
{% endblock javascript %}